# Generated by Django 5.0.2 on 2024-05-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='eth_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
