# Generated by Django 5.0.2 on 2024-05-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='priivate_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
